### ISSUE TITLE
CI / CD 파이프라인 구축

### ISSUE THREAD

**Issue by pwrwpw** [threeback/kicketing-back#47]
### 🤔 Describe

백엔드 서버를 배포하기 위해 CI/CD 파이프라인을 설정

### ✅ Tasks

* [x] Google Cloud Platform에 개발 테스트 서버 구축
* [x] CI 와 CD 파이프라인 작성
* [x] master 브랜치에 pr이 올경우 자동으로 빌드되어 배포하도록 수정

### 🙋🏻 More

🏃‍♀️🏃‍♀️
