### ISSUE TITLE
공연에 대한 예매 가능한 날짜 및 정보 출력 기능 추가

### ISSUE THREAD

**Issue by pwrwpw** [threeback/kicketing-back#65]
### 📄 Describe

이 기능은 사용자들이 공연 예매 가능한 날짜와 관련 정보를 쉽게 확인할 수  있는 기능을 만듭니다.
이는 날짜, 가능한 좌석 수, 회차, 출연하는 배우를 표시하는 것을 포함합니다.

### ✅ Tasks

- [x] 공연 예매 가능한 날짜 제공
- [x] 가능한 좌석 수 제공
- [x] 공연 회차 정보 제공

### 🙋🏻 More

🫡
