### ISSUE TITLE
DB 커넥션 설정

### ISSUE THREAD

**Issue by CodingApe9** [threeback/kicketing-back#69]
### 🤔 Describe

커넥션이 너무 오래 유지되거나 누수되고 있어 커넥션 풀 설정 및 timeout 설정이 필요합니다.

### ✅ Tasks

- [ ] maximum-pool-size 설정
- [ ] idle-timeout 설정
- [ ] max-lifetime 설정
- [ ] connection-timeout 설정
- [ ] leak-detection-threshold 설정
