### ISSUE TITLE
공연 검색 기능

### ISSUE THREAD

**Issue by pwrwpw** [threeback/kicketing-back#93]
### 📄 Describe

엘라스틱서치를 통해 공연을 검색할 수 있는 기능을 추가할 예정입니다!!

### ✅ Tasks

+ [x] Logstash 설정
+ [x] Elasticsearch 서버 설치 및 설정
+ [x] Elasticsearch 인덱스와 매핑되는 Performance 클래스 작성
+ [x] 검색 API 구현
